### ISSUE TITLE
Missing chapter 1 in the icd_meta_chapters table?

### ISSUE THREAD

**Issue by thoen** [edonnachie/ICD10gm#14]
Hello Mr. Donnachie,
first of all, thanks a lot for making this great package. Thanks to you I think I will able to save a lot of time writing reports.

I've noticed that chapter 1 A00-B99  Bestimmte infektiöse und parasitäre Krankheiten seems to be missing from the table icd_meta_chapters. Is this a bug?

Kind regards,
Haavard Thoen

**Comment by thoen** [comment]
chap1 <- data.frame(year = c(2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004), 
                         chapter = c(1), 
                         chapter_roman = 1, 
                         chapter_label = "Bestimmte infektiöse und parasitäre Krankheiten")
icd_meta_chapters <- rbind(icd_meta_chapters, chap1)

**Comment by edonnachie** [comment]
Thank you. That was indeed a bug in the script that reads in the metadata.

The version on github is now corrected, and also contains data for 2021. One I've updated the vignette on Covid-19 codes, I'll send the updated version to CRAN.

**Comment by thoen** [comment]
Hello Mr. Donnachie,
thank you for the quick correction and the feedback.

Kind regards,
Haavard Thoen
